<?php
include "FusionChartsFree/FusionCharts.php";
include "header.phtml";
?>
<div style=" text-align:center">
	<h1 class='title'>考试结束</h1>
    </br>
    <div id="chart">
    <embed src="../../public/Charts/FCF_Column2D.swf?chartWidth=600&chartHeight=300" flashVars="&dataXML=<?php echo $this->dataXML; ?>" quality="high" width="600" height="300" name="Column3D" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
    </div>
	</br>
	<div id="info">
	<p style="color:#f00">以上成绩为客观题成绩。</p>
	</div>
</div>
<?php include "footer.phtml" ?>
