

 </div>

    <div id="close"><img src="../../public/images/stuindex/dialog_close.gif"></div>
    <div id="resetPwd" class="corner"> 
            <h2>修改密码</h2><br/>
        	<form>
            	<div>
                	<input type="password" name="password" /><span>旧密码</span>
                </div><br/>
                <div>
                	<input type="password" name="newpassword" /><span>新密码</span>
                </div><br/>
                <div>
                	<input type="password" name="newpassword2" /><span>确认新密码</span>
                </div><br/>
                <div id="notice"></div>
                <input class="btn_sub" type="button" value="提交">
            </form>
	</div>

	</div>
</div>	
</body>
</html>
