<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>
	<h2>学生界面</h2>
	<hr/>
	<div style=" float:left; border-right:1px solid #000000; width:150px;">
		<a href='resetpassword'>修改密码</a><br><br>
		<a href='showexamtime'>查询考试时间</a><br><br>
		<a href='showexamrecord'>查看已考记录</a><br><br>
		<a href='reexam'>重考</a><br><br>
		<a href='quit'>退出</a><br><br>
	</div>