<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>EnglishExamOnline-Student</title>
<link rel="stylesheet" type="text/css" href="../../public/css/studentindex.css">
<script type="text/javascript" src="../../public/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../../public/js/jquery_corner.js"></script>
<script type="text/javascript" src="../../public/js/studentindex.js"></script>
</head>
<body>
	<div id="header" class="corner">
		<div id="logo"><img src="../../public/images/stuindex/logo2.png" /></div>
            <ul id="menu">
                <li id="showexamtime" class="corner">考试查询</li>					
                <li id="reexam" class="corner">重考查询</li>		
                <li id="showexamrecord" class="corner">考试记录</li>			
            </ul>
            <div id="control" class="corner">
				<span class="fm">欢迎您：<span id="showUsername"><?php echo $this->username; ?></span></span>
                <a id="changepwd" class="fm">[修改密码]</a>
                <a id="exit" class="fm" href="quit">退出</a>
            </div>
	</div>
	
    <div id="main" class="corner">
		<!-- 加载的内容 -->
			 <?php echo $this->render('student/showexamtime.phtml'); ?>
    
    </div>
    <div id="close"><img src="../../public/images/stuindex/dialog_close.gif"></div>
    <div id="resetPwd" class="corner"> 
            <h2>修改密码</h2><br/>
        	<form>
            	<div>
                	<input type="password" name="password" /><span>旧密码</span>
                </div><br/>
                <div>
                	<input type="password" name="newpassword" /><span>新密码</span>
                </div><br/>
                <div>
                	<input type="password" name="newpassword2" /><span>确认新密码</span>
                </div><br/>
                <div id="notice"></div>
                <input class="btn_sub" type="button" value="提交">
            </form>
    </div>
</body>

</html>
