<?php  include_once 'header.phtml';?>

<script type="text/javascript">	
$(document).ready(function(){
	$('#reexam').css('background','url(../../public/images/menu_btn.gif)').find('a').css('color','#fff');
})
</script>
<table>
	<caption>重考列表</caption>
	<tr>
		<th>试卷名</th>
		<th>重考部分</th>
		<th>设置时间</th>
		<th>状态</th>
	</tr>
<?php 
	if(is_array($this->result))
	{
		foreach ($this->result as $value)
		{
?>
		<tr>
		<td><?php echo $value['name']?></td>
		<td><?php echo $value['parts']?></td>
		<td><?php echo $value['time']?></td>
		<td><a style="color:#E00" href="doreexam?examination_id=<?php echo $value['examination_id'];?>&paper_id=<?php	echo $value['paper_id'];?>">进入考试</a></td>
		</tr>
<?php
		}
	}
?>
</table>

<?php include_once 'footer.phtml';?>