<?php  include_once 'header.phtml';?>

<div style="float:left; margin-left:30px;">
<h2>重考</h2>
<table border=1>
	<tr>
		<td>试卷名</td>
		<td>重考部分</td>
		<td>设置时间</td>
		<td>状态</td>
	</tr>
<?php 
	if(is_array($this->result))
	{
		foreach ($this->result as $value)
		{
?>
		<tr>
		<td><?php echo $value['name']?></td>
		<td><?php echo $value['parts']?></td>
		<td><?php echo $value['time']?></td>
		<td><a href="doreexam?examination_id=<?php echo $value['examination_id'];?>&paper_id=<?php	echo $value['paper_id'];?>">进入考试</a></td>
		</tr>
<?php
		}
	}
	else {
		echo $this->result;
	}
?>
</table>
</div>


<?php include_once 'footer.phtml';?>