<?php  include_once 'header.phtml';?>
	
	<div style="border:1px #CCC solid; width:150px; top:150px; position:fixed; right:30px; padding:10px;">
		<?php
			//显示试卷有几部分
			if($this->partNum)
			{
				for($i=1; $i<=$this->partNum; $i++)
				{
					echo '<a href="showpaperandanswer?examination_id='.$this->examinationId.'&paper_id='.$this->paperId.'&part='.$i.'">第'.$i.'部分</a><br/>';
				}
			}
		?>
	</div>
		
	<h3>试题</h3>
	<iframe id="paper_frame" src="../../public/exam/<?php echo $this->tpaper; ?>"></iframe>
	<br/><br/>
	<h3>答案</h3>
	<div id="answer_show">
		<div id="right_answer">
			正确答案：<br/>
			<?php echo $this->paperAnswer; ?>
		</div>
		<div id="your_answer">
			你的答案：<br/>
			<?php echo $this->stuAnswer; ?>
		</div>
		<div style="clear:both"></div>
	</div>
</div>

<?php include_once 'footer.phtml';?>