<?php  include_once 'header.phtml';?>
<div style="float:left; margin-left:30px;">
<h2>已考记录</h2>
<table border=1>
	<tr>
		<td>试卷名</td>
		<td>分类</td>
		<td>开始时间</td>
		<td>结束时间</td>
		<td>分数</td>
		<td></td>
	</tr>
<?php 
	if(is_array($this->result))
	{
		foreach ($this->result as $value)
		{
?>
		<tr>
		<td><?php echo $value['name']?></td>
		<td><?php echo $value['category_id']?></td>
		<td><?php echo $value['startTime']?></td>
		<td><?php echo $value['endTime']?></td>
		<td><?php echo '分数';?></td>
		<td><?php echo '<a href="showpaperandanswer?paper_id='.$value['paper_id'].'&part=1">查看试题和答案</a>';?></td>
		</tr>
<?php
		}
	}
	else {
		echo $this->result;
	}
?>
</table>
</div>
<?php include_once 'footer.phtml';?>