<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Flexigrid</title>
<style type="text/css">
<!--
*{ padding:0; margin:0;}
html{ overflow-x:hidden;}
body{ background:#fff;}
.warning_text { color:blue;font-weight:bold;}
-->
</style>
<link rel="stylesheet" type="text/css" href="../../public/css/flexigrid.css" />
<script type="text/javascript" src="../../public/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../../public/js/flexigrid.js"></script>
<script type="text/javascript" src="../../public/js/managepapercategory.js"></script>
</head>

<body>
<table id="flex1" style="display:none"></table>


	<div id="dialog">
	   <form id="dialog_form" name="dialog_form" action="#">
		 <input type="hidden" name="id" /><br/><br/>
		 <div class="dia_mb">试卷类型名称  <input class="input_text" type="text" name="name"></div>
		<br/><br/><br/>
		 <div class="dia_btn">
			 <span class="btns" id="okBtn">OK</span>
			 <span class="btns" id="cancelBtn">Cancel</span>
		 </div>
	   </form>
	</div>
	<div id="alert_msg"></div>
	<div id="confirm_msg">
		<span class="confirm_text"></span><br/>
		<span class="warning_text"></span><br/>
		<span class="btns" id="confirm_yes" class="">Yes</span>
		<span class="btns" id="confirm_cancel">Cancel</span>
	</div>
</body>
</html>

