<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>教师管理页面</title>
<script type="text/javascript" language="javascript" src="../../public/js/jquery-1.4.2.js"></script>
<style type="text/css"><!--  
th{  
	background-color: RGB(192,222,122)
}  
.td1{ 	
	background-color:blue; 
}  
--></style>

</head>
<body>
	<h2>教师界面</h2>
	<hr/>
	<div style=" float:left; border-right:1px solid #000000; width:150px;">
		<?php echo $this->showlist; ?>
		<a href="quit">退出</a>
	</div>
