<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache, must-revalidate"> <!-- 清除缓存 -->
<title>管理</title>
<script type="text/javascript" language="javascript" src="../../public/js/jquery-1.2.3.js"></script>
<link rel="stylesheet" type="text/css" href="../../public/css/flexigrid/flexigrid.css">
<link rel="stylesheet" type="text/css" href="../../public/css/teacher.css">
<script type="text/javascript" src="../../public/js/flexigrid_with_checkbox.js"></script>

</head>
<body>