<table id="flex1" style="display:none"></table>
	<div id="dialog">
       <form id="dialog_form" name="dialog_form" action="#">
			<input type="hidden" name="id" />
	  		<div class="dia_mb"><span>I&nbsp;&nbsp;D </span> <input class="input_dis" type="text" disabled="disabled" name='dis_id' /></div>
            <div class="dia_mb">登录名  <input maxlength="11" class="input_text" type="text" name="username" /></div>
            <div class="dia_mb">姓&nbsp;&nbsp;名  <input type="text" class="input_text" name="name" /></div>
            <span>性&nbsp;&nbsp;别  </span>
            <input type="radio" name="sex" checked="checked" value="男">男
            <input type="radio" name="sex" value="女">女
            <br/>
            <br/><br/>
		 <span class="notice"></span><br/>
         <div class="dia_btn">
             <span class="btns" id="okBtn">OK</span>
             <span class="btns" id="cancelBtn">Cancel</span>
         </div>
       </form>
	</div>
	<div id="alert_msg"></div>
	<div id="confirm_msg">
		<span class="confirm_text"></span><br/><br/>
		<span class="btns" id="confirm_yes" class="">Yes</span>
		<span class="btns" id="confirm_cancel">Cancel</span>
	</div>
