<?php  include_once '_header.phtml';?>

<script type="text/javascript" language="javascript" src="../../public/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
	//预览
	/*$(document).ready(function(){
		$('#preview').click(function(){
			var str = CKEDITOR.instances.editor1.getData();
			var maxTopic = document.getElementById('maxTopic').value;
			var minTopic = document.getElementById('minTopic').value;
			$.post('preview',{'editor': str,'maxTopic': maxTopic,'minTopic': minTopic}, function (data){
				$('#showPreview').html(data);
			})
			return false;
		})
	})*/

	//替换提交标识
	function replaceContent(flag,title)
	{		
		document.getElementById("showTitle").textContent = title;
		document.getElementById("partType").value = flag;	
		
		if (CKEDITOR.instances['writing']) {
				CKEDITOR.instances['writing'].destroy();
		}
		if (CKEDITOR.instances['writing_answer']) {
				CKEDITOR.instances['writing_answer'].destroy();
		}
		if (CKEDITOR.instances['editor1']) {
				CKEDITOR.instances['editor1'].destroy();
		}
		
		if(flag == 'writing')
		{
			document.getElementById("editContent").innerHTML = '<textarea class="ckeditor" id="writing" name="writing" rows="15"></textarea> <br/>答案：<textarea class="ckeditor" id="writing_answer" name="writing_answer" rows="15"></textarea>';
			CKEDITOR.replace( 'writing' );
			CKEDITOR.replace( 'writing_answer' );
		}else{
			if(flag == 'fastReading'){
				document.getElementById("editContent").innerHTML = '<textarea class="ckeditor" id="editor1" name="editor1" rows="15"></textarea>开始题号：<input type="text" id="startNum" name="startNum"/>结束题号：<input type="text" id="endNum" name="endNum"/><input id="addBtn" type="button" onclick="add_answer()" value="添加选择题答案" /><br>开始题号：<input type="text" id="fstartNum" name="fstartNum"/>结束题号：<input type="text" id="fendNum" name="fendNum"/><input id="addBtn" type="button" onclick="add_fill_answer()" value="添加填空题答案" /><div id="answers"></div><div id="fanswers"></div><div id="audioFile"></div>';
			}
			else if((flag == 'dictation') || (flag == 'translation')){
				document.getElementById("editContent").innerHTML = '<textarea class="ckeditor" id="editor1" name="editor1" rows="15"></textarea>开始题号：<input type="text" id="fstartNum" name="startNum"/>结束题号：<input type="text" id="fendNum" name="endNum"/><input id="addBtn" type="button" onclick="add_fill_answer()" value="添加填空题答案" /><div id="answers"></div><div id="fanswers"></div><div id="audioFile"></div>';
			}
			else{
				document.getElementById("editContent").innerHTML = '<textarea class="ckeditor" id="editor1" name="editor1" rows="15"></textarea>开始题号：<input type="text" id="startNum" name="startNum"/>结束题号：<input type="text" id="endNum" name="endNum"/><input id="addBtn" type="button" onclick="add_answer()" value="添加选择题答案" /><div id="answers"></div><div id="fanswers"></div><div id="audioFile"></div>';
			}
			CKEDITOR.replace( 'editor1' );
			
			document.getElementById('audioFile').innerHTML = "";
			if((flag == 'shortListening') || (flag =='longListening') || (flag =='dictation'))
			{
				document.getElementById('audioFile').innerHTML = '添加音频：<input type="file" id="audio" name="audio" />';
			}
		}
		
	}
	//添加答案选框
	function add_answer(){
			var str = '<select name="answers[]"><option value="">请选择</option><option value="A">A</option><option value="B">B</option><option value="C">C</option><option value="D">D</option></select>';
			var startNum = parseInt(document.getElementById('startNum').value);
			var endNum = parseInt(document.getElementById('endNum').value);
			document.getElementById("answers").innerHTML = "";
			for(var i=startNum; i<=endNum; i++)
			{ 
				document.getElementById("answers").innerHTML += " " + i + "." + str;
			}
	}
	function add_fill_answer(){
			var str = '<input type="text" name="answers[]" />';
			var fstartNum = parseInt(document.getElementById('fstartNum').value);
			var fendNum = parseInt(document.getElementById('fendNum').value);
		  document.getElementById("fanswers").innerHTML = "";
			for(var ii=fstartNum; ii<= fendNum; ii++)
			{ 
				document.getElementById("fanswers").innerHTML += " " + ii + "." + str;
			}
	}
	
</script>
<div style="float:left; margin-left:30px;">

	<form name="readingForm" action="" enctype="multipart/form-data" method="post">
		<h2>上传试卷</h2>
		<div style="border:1px #CCC solid; width:150px; top:150px; right:30px;position:absolute; padding:10px;">
		<a href="JavaScript:replaceContent('writing','写作')">写作</a><br>
		<a href="JavaScript:replaceContent('fastReading','快速阅读')">快速阅读</a><br>
		<a href="JavaScript:replaceContent('shortListening','听力短对话')">听力短对话</a><br>
		<a href="JavaScript:replaceContent('longListening','听力长对话或短文')">听力长对话或短文</a><br>
		<a href="JavaScript:replaceContent('dictation','听力听写')">听力听写</a><br>
		<a href="JavaScript:replaceContent('reading','阅读')">阅读</a><br>
		<a href="JavaScript:replaceContent('cloze','完形填空')">完形填空</a><br>
		<a href="JavaScript:replaceContent('translation','翻译')">翻译</a><br><br/>
		<a style="color:#F00" href="editupexam">完成上传试题</a><br>
		
		<div id="showSummarize" style="float:right; margin-top:20px; width:150px; border:#CCC 1px solid;">
		已上传的试题部分：
		<?php
			if($this->temporaryRartList)
			{
				$i=0;
				foreach($this->temporaryRartList as $value)
				{
					$i++;
					echo $i.".".$value['name']."<br/>";
				}
			}
		?>
		</div>
		</div>

		<div id="" style="width:700px;">
		<input id="preview" type="button" value="预览"><br/>
			<div id="showTitle" style="color:#006; font-weight:bold; font-size:20px; text-align:center"></div>
			<div id="editContent">
				<b>作文：</b><textarea class="ckeditor" id="writing" name="writing" rows="15"></textarea> <br/>答案：<textarea class="ckeditor" id="writing_answer" name="writing_answer" rows="15"></textarea>
			</div>
			本题总分：<input type="text" name="score" /><br/>
			<input type="hidden" id="partType" name="partType" value="reading"><br>
			<input type="button" name="" onClick="readingForm.submit()" style="color:#F00" value="提交" />
			<br/><br/><br/>

		</div>
			
	</form>
	<div id="showPreview"></div>
</div>

<?php include_once '_footer.phtml';?>