<?php  include_once '_header.phtml';?>

<script type="text/javascript">
$(document).ready(function(){
	$('#add').click(function(){
		var name=document.getElementById('name').value;
		var username=document.getElementById('username').value;
		var sex=document.getElementById('sex').value;
		var password=document.getElementById('password').value;
		$.post("addstudent",{'name':name, 'username':username, 'sex':sex,
		'password':password },function(data){
			document.getElementById('getData').innerHTML = data;
		})
	})
})
</script>

<div style="float:left; margin-left:30px;">
    <form method="post" action="">
        <br>添加学生
        <br>姓名：<input type="text" id="name" name="name"/>
        <br>学号：<input type="text" id="username" name="username"/>
        <br>性别：<input type="text" id="sex" name="sex"/>
        <br>密码：<input type="text" id="password" name="password"/>
        <br><input type="button" id="add" name="add" value="添加"/>
    </form>
    
    <div id='getData'></div>
</div>

<?php include_once '_footer.phtml';?>