<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>版本</title>
<style type="text/css">
<!--
*{ padding:0; margin:0;}
body{ background:#1e5b9c; text-align:center; font-size:12px; color:#FFF;}
-->
</style>
</head>

<body>
<p>Copyright By 广西大学计网081团队 2011-04-18</p>
</body>
</html>
