<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>header</title>
<link rel="stylesheet" type="text/css" href="../../public/css/teacher_header.css" />
</style>
</head>

<body>
	<div id="head">
    	<img id="logo" src="../../public/images/admin/logo.png" />
        <a id="exit" class="fm" href="quit" target="_top">退出</a>
        <a id="changepwd" class="fm" href="resetpassword" target="con">修改密码</a>
        <span class="fm"><img src="../../public/images/admin/message.gif" /><a href="#">消息(<span> <?php echo $this->message_num; ?> </span>)</a></span>
        <span class="fm">欢迎您：<?php echo $this->username; ?></span>
	</div>
</body>
</html>

