<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>header</title>
<style type="text/css">
<!--
*{ padding:0; margin:0;}
a{ text-decoration:none; color:#FFF;}
#logo{ border:none; float:left; margin-left:20px;margin-top:10px;}
body{font-family:"微软雅黑", Arial, "MS Sans Serif", System;	}
#head{
	height:90px;
	width:100%;
	background:url(../../public/images/head_bg.png) repeat-x;
	}
.fm{ float:right; margin-top:65px; margin-right:20px; color:#FFF; font-size:14px;}
a.fm{ display:block; height:16px; width:80px; text-indent:20px;}
a.fm:hover{ text-decoration:underline;}
a#exit{ background:url(../../public/images/exit.gif)  no-repeat;}
a#changepwd{ background:url(../../public/images/key.gif) no-repeat;}
span.fm span{ color:#F00;}
span.fm a:hover{ text-decoration:underline;}
-->
</style>
</head>

<body>
	<div id="head">
    	<img id="logo" src="../../public/images/logo.png" />
        <a id="exit" class="fm" href="quit">退出</a>
        <a id="changepwd" class="fm" href="#">修改密码</a>
        <span class="fm"><img src="../../public/images/message.gif" /><a href="#">消息(<span> 12 </span>)</a></span>
        <span class="fm">欢迎您： admin</span>
    </div>

