<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>英语考试系统后台管理</title>
</head>
	<frameset rows="90,*,15" frameborder="no"  border="0" framespacing="0">
  		<frame src="header" name="header" noresize="noresize"  scrolling="No" />
 		<frameset cols="160,*" frameborder="no"  border="0" framespacing="0">
            <frame src="quickmenu" name="menu" />
            <frame src="" name="con"  noresize="noresize"  />
		</frameset>
  		<frame src="footer" name="footer" noresize="noresize"  scrolling="No" />
	</frameset>
    
<noframes>
<body>
	<p>你的浏览器不支持框架！</p>
</body>
</noframes>
</html>
