<?php  
include_once '_header.phtml';?>
<div style="float:left; margin-left:30px;">

<form action="manageteacher" method="post">
<input type="text" name="Name" />
<input type="submit" name="submit" value="搜索" />
<input type="button" value="添加教师" name="add" /><br/>

<div id="addteacherFrame">
	用户名：<input type="text" name="username"/><br/> 
	密码：<input type="text" name="password"/><br/> 
	真实姓名：<input type="text" name="name"/><br/> 
	性别：<input type="radio" name="sex" value="男"/>男 <input type="radio" name="sex" value="女"/>女<br/> 
</div>
</form>

<?php
$result = $this->teacherlist;
if(!is_array($result)) echo '查无教师';
include '_table.phtml';

include_once '_footer.phtml'; 

?>
