<?php  include_once '_header.phtml';?>

	<table id="flex1" style="display:none"></table>
	<script type="text/javascript" src="../../public/js/manage_score.js"></script>
<div id="dialog">
       <form id="dialog_form" name="dialog_form" action="#">
			<input type="hidden" name="id" />
	  		<input class="input_dis" type="hidden" name='student_id' />
				<input class="input_dis" type="hidden" name='examination_id' />
					<div class="dia_mb"><span>&nbsp;&nbsp;学 生</span> <input class="input_dis" type="text" disabled="disabled" name='name' /></div>
					<div class="dia_mb"><span>&nbsp;考试名</span> <input class="input_dis" type="text" disabled="disabled" name='examination_name' /></div>
          <div class="dia_mb">各部分成绩<input type="text" class="input_text" name="parts_score" /></div>

            <br/>
		 <span class="notice"></span><br/>
         <div class="dia_btn">
             <span class="btns" id="okBtn">OK</span>
             <span class="btns" id="cancelBtn">Cancel</span>
         </div>
       </form>
	</div>
	<div id="alert_msg"></div>
	<div id="confirm_msg">
		<span class="confirm_text"></span><br/><br/>
		<span class="btns" id="confirm_yes">Yes</span>
		<span class="btns" id="confirm_cancel">Cancel</span>
	</div>
    <div id="chose_class">
		<span>请选择班级：</span><br/><br/>
		<span class="chose_class_btns"></span>
    </div>
<?php include_once '_footer.phtml';?>
