<?php  include_once 'header.phtml';?>
<div style="float:left; margin-left:30px;">
<p>可操作的班级数:<?php echo count($this->classes)?></p>
选择您要操作的班级:
<SELECT ID="selectclass" NAME="class" SIZE="1">
<?php foreach($this->classes as $value) 
{ 
	echo '<OPTION VALUE='.$value['id'].'>'.$value['class_name'].'</OPTION>';
}
?>
</SELECT>
<b id="loading" style="display:none">请求载入中。。。</b>
<script type="text/javascript" language="javascript">
//ajax请求学生列表
$('#selectclass').change(function (){  
	$.post(  
		'showstudenttablelist',  
		{  
			'classid': $('#selectclass').val(),
				'classname':$('#selectclass').find("option:selected").text()
		},  
		function (data){  $('#tablelist').html(data); }
	);  
}
);
$("#loading").ajaxStart(function(){
    $(this).show();
 }); 
$("#loading").ajaxSuccess(function(){
	$(this).hide();
}
 );


</script>
    <div id="tablelist">
	<?php echo $this->render('/teacher/showstudenttablelist.phtml')?>
	</div>
</div>
<?php include_once 'footer.phtml';?>
