<?php  include_once '_header.phtml';?>
	
	<script type="text/javascript" src="../../public/js/flexigrid_with_checkbox.js"></script>
	<table id="flex1" style="display:none"></table>
<div id="dialog">
       <form id="dialog_form" name="dialog_form" action="#">
			<input type="hidden" name="id" />
	  		<div class="dia_mb"><span>&nbsp;&nbsp;&nbsp;ID</span> <input class="input_dis" type="text" disabled="disabled" name='id' /></div>
            <div class="dia_mb">&nbsp;&nbsp;试卷名<input maxlength="11" class="input_text" type="text" name="title" /></div>
            <div class="dia_mb">试卷说明<input type="text" class="input_text" name="introduction" /></div>
            <div class="dia_mb">试卷时长<input type="text" class="input_text" name="time" /></div>
            <br/>
		 <span class="notice"></span><br/>
         <div class="dia_btn">
             <span class="btns" id="okBtn">OK</span>
             <span class="btns" id="cancelBtn">Cancel</span>
         </div>
       </form>
	</div>
	<div id="alert_msg"></div>
	<div id="confirm_msg">
		<span class="confirm_text"></span><br/><br/>
		<span class="btns" id="confirm_yes">Yes</span>
		<span class="btns" id="confirm_cancel">Cancel</span>
	</div>
	<script type="text/javascript" src="../../public/js/manage_paper.js"></script>
	
<?php include_once '_footer.phtml';?>
