<?php  include_once 'header.phtml';?>

<div style="float:left; margin-left:30px;">

<form action="manageleader" method="post">
<input type="text" name="leaderName" />
<input type="submit" name="submit" value="搜索" />
<input type="button" value="添加系主任" name="addLeader" /><br/>

<div id="addLeaderFrame">
	用户名：<input type="text" name="username"/><br/> 
	密码：<input type="text" name="password"/><br/> 
	真实姓名：<input type="text" name="name"/><br/> 
	性别：<input type="radio" name="sex" value="男"/>男 <input type="radio" name="sex" value="女"/>女<br/> 
</div>

</form>
<?php
if(is_array($this->leaderList))
{
	foreach($this->leaderList as $value)
	{
		echo $value['name']."删除，编辑。。。<br/>";
	}
}
else 
{
	echo $this->leaderList;
}
?>

</div>

<?php include_once 'footer.phtml';?>
