<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>学生管理</title>
<link rel="stylesheet" type="text/css" href="../../public/css/flexigrid.css" />
<script type="text/javascript" src="../../public/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../../public/js/flexigrid.js"></script>
<script type="text/javascript" src="../../public/js/managestudent.js"></script>
</head>
<body>
</script>
    <div id="tablelist">
	<?php echo $this->render('/teacher/showstudenttablelist.phtml');?>
	</div>
</div>
</body>
</html>
