<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>快速菜单</title>
<link rel="stylesheet" type="text/css" href="../../public/css/teacher_quickmenu.css" />
<script type="text/javascript" src="../../public/js/jquery-1.4.2.js"></script>
<script type="text/javascript">
<!--
$(function(){
	$('#main p').click(function(){
		$(this).css('background','url(../../public/images/admin/quickMenu_open.gif)').next('ul').stop(true, true).slideDown();
		$(this).parent('li').siblings('li').find('p').css('background','url(../../public/images/admin/quickMenu.gif)').next('ul').stop(true, true).slideUp();		
	});
})
-->
</script>
</head>

<body>
<div id="nav_menu"></div>
<ul id="main">
	<li>
    	<p>考试设置</p>
        <ul>
        	<li><a href="http://www.baidu.com" target="con">考试列表</a></li>
            <li><a href="setexam" target="con">设置考试</a></li>
            <li><a href="setreexam" target="con">设置重考</a></li>
        </ul>
    </li>
    <li>
    	<p>试卷管理</p>
        <ul>
        	<li><a href="manageexam" target="con">试卷列表</a></li>
            <li><a href="addexam" target="con">添加试卷</a></li>
            <li><a href="#" target="con">编辑试卷分类</a></li>
        </ul>
    </li>
    <li>
    	<p>学生管理</p>
        <ul>
        	<li><a href="managestudent" target="con">学生列表</a></li>
            <li><a href="#" target="con">快速添加学生</a></li>
        </ul>
    </li>
    <li>
    	<p>成绩信息</p>
        <ul>
        	<li><a href="#" target="con">本班成绩</a></li>
            <li><a href="#" target="con">年级成绩概览</a></li>
        </ul>
    </li>
    <li>
    	<p>系主任管理</p>
        <ul>
        	<li><a href="manageleader" target="con">主任列表</a></li>
            <li><a href="editleader" target="con">设置管理的教师</a></li>
        </ul>
    </li>
    <li>
    	<p>教师管理</p>
        <ul>
        	<li><a href="manageteacher" target="con">教师列表</a></li>
            <li><a href="#" target="con">添加教师</a></li>
        </ul>
    </li>
    <li>
    	<p>系统设置</p>
        <ul>
        	<li><a href="#" target="con">系统公告</a></li>
            <li><a href="backup" target="con">数据备份</a></li>
        </ul>
    </li>
</ul>
</body>
</html>
