<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>快速菜单</title>
<link rel="stylesheet" type="text/css" href="../../public/css/teacher_quickmenu.css" />
<script type="text/javascript" src="../../public/js/jquery-1.4.2.js"></script>
<script type="text/javascript">
<!--
$(function(){
	$('#main p').click(function(){
		$(this).css('background','url(../../public/images/admin/quickMenu_open.gif)').next('ul').stop(true, true).slideDown();
		$(this).parent('li').siblings('li').find('p').css('background','url(../../public/images/admin/quickMenu.gif)').next('ul').stop(true, true).slideUp();		
	});
})
-->
</script>
</head>

<body>
<div id="nav_menu"></div>
<?php echo $this->showlist; ?>
</body>
</html>
