<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>管理</title>

<script type="text/javascript" language="javascript" src="../../public/js/jquery-1.3.2.min.js"></script>
</head>
<body style="background:#efefef;">
<script type="text/javascript" src="../js/jquery_corner.js"></script>
<script type="text/javascript">
	$('.corner').corner('10px');
</script>
<div class="corner" style=" width:50%; margin:30px auto; background:#fff;padding:15px;">
	<b style="color:#06C; font-size:20px;"><big>修改密码</big></b><br/><br/>
	<span style="color:#ff0000"><?=$this->error; ?></span>
	<br/>
	<form id="resetPass" action="resetpassword" method="post">
		您的用户名：
		<span style="color:#00F;"><?=$this->username; ?></span>
		<br><br>
		您的旧密码：
		<input id="oldpassword" name="password" type="password" />
		<br><br>
		您的新密码：
		<input id="newpassword" name="newpassword" type="password" />
		<br><br>
		新密码确认：
		<input id="newpassword2" name="newpassword2" type="password" />
		<br><br>
		<script type="text/javascript">
		function sub_check(){
			var oldpass = document.getElementById('oldpassword').value;
			var pass1 = document.getElementById('newpassword').value;
			var pass2 = document.getElementById('newpassword2').value;
	
			if(oldpass=="" || pass1=="" || pass2 == "")
			{
				alert('请把内容填写完整！');
			}
			else
			{
				if(pass1 == pass2)
				{
					document.getElementById("resetPass").submit();
				}
				else
				{
					alert('两次输入的密码不一致！');
				} 
			}	
		}
		</script>
		<input type="button" value="确定" onclick="sub_check()">
	</form>
	<br>
	<p style="color:#009">
		<?php echo $this->text; ?>
	</p>
</div>

</body>
</html>
