<?php  include_once 'header.phtml';?>
<div style="float:left; margin-left:30px;">
<h2>修改密码</h2>
<span style="color:#ff0000"><?=$this->error; ?></span>
<form id="resetPass" action="resetpassword" method="post">
	您的用户名：
	<?=$this->number; ?>
	<br><br>
	您的旧密码：
	<input id="oldpassword" name="password" type="password" />
	<br><br>
	您的新密码：
	<input id="newpassword" name="newpassword" type="password" />
	<br><br>
	新密码确认：
	<input id="newpassword2" name="newpassword2" type="password" />
	<br><br>
	<script type="text/javascript">
	function check(){
		var oldpass = document.getElementById('oldpassword').value;
		var pass1 = document.getElementById('newpassword').value;
		var pass2 = document.getElementById('newpassword2').value;

		if(oldpass=="" || pass1=="" || pass2 == "")
		{
			alert('请把内容填写完整！');
		}
		else
		{
			if(pass1 == pass2)
			{
				resetPass.submit();
			}
			else
			{
				alert('两次输入的密码不一致！');
			} 
		}	
	}
	</script>
	<input type="button" value="确定" onclick="check()">
</form>
<p style="color: #00ff00">
	<?=$this->text; ?>
</p>
</div>
<?php include_once 'footer.phtml';?>