<?php  include_once '_header.phtml';?>

<div style=" width:300px; margin:30px;">
	<b><big>修改密码</big></b><br/><br/>
	<span style="color:#ff0000"><?=$this->error; ?></span>
	<br/>
	<form id="resetPass" action="resetpassword" method="post">
		您的用户名：
		<span style="color:#00F;"><?=$this->username; ?></span>
		<br><br>
		您的旧密码：
		<input id="oldpassword" name="password" type="password" />
		<br><br>
		您的新密码：
		<input id="newpassword" name="newpassword" type="password" />
		<br><br>
		新密码确认：
		<input id="newpassword2" name="newpassword2" type="password" />
		<br><br>
		<script type="text/javascript">
		function sub_check(){
			var oldpass = document.getElementById('oldpassword').value;
			var pass1 = document.getElementById('newpassword').value;
			var pass2 = document.getElementById('newpassword2').value;
	
			if(oldpass=="" || pass1=="" || pass2 == "")
			{
				alert('请把内容填写完整！');
			}
			else
			{
				if(pass1 == pass2)
				{
					document.getElementById("resetPass").submit();
				}
				else
				{
					alert('两次输入的密码不一致！');
				} 
			}	
		}
		</script>
		<input type="button" value="确定" onclick="sub_check()">
	</form>
	<br>
	<p style="color:#009">
		<?php echo $this->text; ?>
	</p>
</div>
<?php include_once '_footer.phtml';?>