<?php  include_once '_header.phtml';?>
<script type="text/javascript">
	function showPaperList(category_id)
	{
		url = "setexam";
		$.post(url,{'category_id': category_id}, function (data){
			$('#paperList').html(data);
			
		});
	}
	//设置已选择的试卷名和试卷ID
	function setPaperName(title,paper_id)
	{
		document.getElementById("paperTitle").textContent = title;
		document.getElementById("paperName").value = title;
		document.getElementById("paperId").value = paper_id;
	}
	//搜索试卷
	function searchPaper()
	{
		title = document.getElementById("getSearchName").value;
		$.post('setexam',{'searchByName':title},function(data){
			$('#paperList').html(data);
			});
	}
</script>
<div style="float:left; margin-left:30px;">
	<h2>设置考试</h2>
	<span style="color:#F00"><?php echo $this->error."<br/>"; ?></span>
	<form name="form1" action="setexam" method="post">
	
	试卷名：<span id="paperTitle"> </span><br/><br/>
				<input type="hidden" id="paperName" name="paperName" value="" />
				<input type="hidden" id="paperId" name="paperId" value="" />
	选择试卷类别：
	<?php
	if(is_array($this->categoryList))
	{
		foreach($this->categoryList as $value)
		{
			echo "<input type='radio' onClick='showPaperList(".$value['id'].")' name='paperCategoryID' value='".$value['id']."'>".$value['name']."&nbsp;&nbsp;";
		}	
	}
	?>
	<br/>
	<input type="text" id="getSearchName" name="getSearchName" /><input type="button" onClick="JavaScript:searchPaper()" value="搜索试卷" /><br/><br/>
	
	<!-- 试卷显示列表 -->
	<div id="showExamList" style="border:1px #CCC solid; padding:10px;">
	<b>试卷列表</b><br>
	<div id="paperList"></div>
		<?php
			if(is_array($this->getListByTitle))
			{
				foreach($this->getListByTitle as $value)
				{
					echo "<a href=\"JavaScript:setPaperName('".$value['title']."','".$value['id']."')\">".$value['title']."</a><br/>";
				}
			}else
			{
				echo $this->noSearchResult."<br>";
			}
		?>
	</div><br/>
	
	选择班级：
	<?php 
		if(is_array($this->showClassList))
		{
			foreach($this->showClassList as $value)
			{
				echo '<input type="checkbox" name="class_id[]" value="'.$value['id'].'"/>'.$value['class_name'];
			}
		}
		else
		{
			echo "没有您管理的班级";
		}
	?>
	<br/><br/>
	排除的学生：<input type="text" name="rejectStus" /><br/><br/>
	其他可以参加考试的学生：<input type="text" name="otherStus" /><br/><br/>
	
	开始考试时间：<input type="text" name="startTime" /><br/><br/>
	结束考试时间：<input type="text" name="endTime" /><br/><br/>
	
	<div>
	<?php
		
	?>
	</div>
	<input type="button" name="setExamSubmit" onClick="form1.submit()"  value="确定" />
	</form>
</div>
<script type="text/javascript">
	
</script>

<?php include_once '_footer.phtml';?>
