<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>管理</title>
<style type="text/css">
<!--
*{ padding:0; margin:0;}
body{ background:#efefef; font-family:"微软雅黑", Arial, "MS Sans Serif", System; font-size:14px; padding-bottom:15px;s}
h1{ color:#06C; font-size:22px;}
a{ text-decoration:none; color:#000;}
a:hover{ text-decoration:underline;color:#900;}

html{ overflow-x:hidden;}

#main{
	width:90%;
	background:#fff;
	padding:15px;
	margin:10px auto;}
#showExamList{
	width:400px;
	padding:10px;
	background:#C4E1FF;
	margin-bottom:5px;}
#paperTitle{ color:#900;}
#searchBtn,#sub{
	height:22px;
	width:100px;
	text-align:center;
	border:none;
	}
#searchBtn{
	background:url(../images/login_Btn.gif);}
	#sub{background:url(../images/login_Btn_hover.gif); margin-left:200px; margin-top:20px; color:#fff;}
#paperList{
	width:400px;
	list-style:none;}
#paperList li{ display:none;}
#tip span{
	padding:0px 5px;
	background:#C4E1FF;
	margin-left:10px;
	cursor:pointer;
	color:#FFF;}
#tip{
	margin-bottom:5px;}		
-->
</style>
<script type="text/javascript" src="../js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../js/jquery_corner.js"></script>
<script type="text/javascript" src="../../public/js/Calendar.js"></script>
<script language="javascript">
//试卷列表分页
function paging(){
	var len = $('#paperList li').length;
	var no = 10;  //一页显示的条数
	$('#tip span').remove();
	(function(){
		var papers = Math.ceil(len/no);
		if(papers>1){
			for(i=1;i<=papers;i++){
				var btns = "<span>"+i+"</span>";
				$('#tip').append(btns);
			}
			var show_li = '#paperList li:lt('+ no +')';
			$(show_li).show();
		}else{
			$('#paperList li').show();
		}
	})();	
	$('#tip span').live('click',function(){		
			var p = $(this).text();
			$('#paperList li').hide();
			var show_li_l = '#paperList li:lt('+  (p*no)  +')';
			var hide_li_l = '#paperList li:lt('+  (p-1)*no  +')';
			$(show_li_l).show();
			$(hide_li_l).hide();
	});
}
	//日历
  var cdr = new Calendar("cdr");
  document.write(cdr);
  cdr.showMoreDay = true;
</script>
<script type="text/javascript">
	$(function(){
		$('.corner').corner('10px');
	})
	//按分类显示试卷列表
	function showPaperList(category_id)
	{
		url = "setexam";
		$.post(url,{'category_id': category_id}, function (data){
			$('#paperList').html(data);
			paging();
		});
	}
	//设置已选择的试卷名和试卷ID
	function setPaperName(title,paper_id)
	{
		document.getElementById("paperTitle").textContent = title;
		document.getElementById("paperName").value = title;
		document.getElementById("paperId").value = paper_id;
	}
	//搜索试卷
	function searchPaper()
	{
		title = document.getElementById("getSearchName").value;
		$.post('setexam',{'searchByName':title},function(data){
			$('#paperList').html(data);
			paging();	
			});	
	}

	//检查学号是否存在
	$(document).ready(function(){
		$('#checkReject').click(function(){
			$.post('checkstudents',{'checkStuNums':$('#rejectStus').val()}, function(data){
				$('#checkRejectResult').html(data);
			})
		});	
		$('#checkPermit').click(function(){
			$.post('checkstudents',{'checkStuNums':$('#otherStus').val()}, function(data){
				$('#checkPermitResult').html(data);
			})
		})
	})
</script>
</head>
<body>
<div id="main" class="corner">
	<h1>设置考试</h1><br/>
  <span>请选择试卷</span> <span style="margin-left:50px; color:#F00"><?php echo $this->msg; ?></span>
	<br/><br/>
	<form name="form1" action="setexam" method="post">
         <!-- 试卷显示列表 -->
        <b>试卷列表</b>
        <div id="showExamList" class="corner">
            <ul id="paperList">请先选择试卷类别...</ul><br>
        </div>
				<div id="tip">
				</div>
        <input type="text" id="getSearchName" name="getSearchName" />
        <input type="button" id='searchBtn' onClick="JavaScript:searchPaper()" value="搜索试卷" /><br/><br/>
        <span>试卷名：</span><span id="paperTitle">未选择试卷</span><br/><br/>
        <input type="hidden" id="paperName" name="paperName" value="" />
        <input type="hidden" id="paperId" name="paperId" value="" />
        <span>选择试卷类别：</span>
				<?php
				if(is_array($this->categoryList))
				{
					foreach($this->categoryList as $value)
					{
						echo "<input type='radio' onClick='showPaperList(".$value['id'].")' name='paperCategoryID' value='".$value['id']."'>".$value['name']."&nbsp;&nbsp;";
					}	
				}
				?>
				<br/><br/>
    
       	<span>选择班级：</span>
        <?php 
				if(is_array($this->showClassList))
				{
					foreach($this->showClassList as $value)
					{
						echo '<input type="checkbox" name="class_id[]" value="'.$value['id'].'"/>'.$value['class_name']."&nbsp;&nbsp;";
					}
				}
				else
				{
					echo "没有您管理的班级";
				}
				?>	<br/><br/>

        排除的学号（多个用逗号隔开，如: 111,112,113）：<br/>
				<input type="text" style="width:380px;" name="rejectStus" id="rejectStus" /> <input type="button" id="checkReject" value="检查" /> <span id="checkRejectResult"></span><br/><br/>
				班级外允许参加考试的学号（格式同上）：<br/>
				<input type="text" style="width:380px;" name="otherStus" id="otherStus" /> <input type="button" id="checkPermit" value="检查" /> <span id="checkPermitResult"></span><br/><br/>
				
				<div>
					开始考试时间：
					<input type="text" name="startDate" onfocus="cdr.show(this);" value=""/>
					<select class="time_in" name="startHour">
					<script type="text/javascript">
						for(var i=0; i<24; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select> : 
					<select class="time_in" name="startMinute">
					<script type="text/javascript">
						for(var i=0; i<60; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select> : 
					<select class="time_in" name="startSecond">
					<script type="text/javascript">
						for(var i=0; i<60; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select>
				</div><br>						
				<div>
					结束考试时间：
					<input type="text" name="endDate" onfocus="cdr.show(this);" value=""/>
					<select class="time_in" name="endHour">
					<script type="text/javascript">
						for(var i=0; i<24; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select> :
					<select class="time_in" name="endMinute">
					<script type="text/javascript">
						for(var i=0; i<60; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select> : 
					<select class="time_in" name="endSecond">
					<script type="text/javascript">
						for(var i=0; i<60; i++){
							var str = "<option value="+i+">"+i+"</option>";
							document.write(str);
						}
					</script>
					</select>
				</div><br/>		
        <input id="sub" type="button" name="setExamSubmit" onClick="form1.submit()"  value="确定" />
	</form>
</div>

<script type="text/javascript">

	

</script>





</body>

</html>