<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>管理</title>
<style type="text/css">
<!--
*{ padding:0; margin:0;}
body{ background:#efefef; font-family:"微软雅黑", Arial, "MS Sans Serif", System; font-size:14px;}
h1{ color:#06C; font-size:22px;}
html{ overflow-x:hidden;}
a{ text-decoration:none; color:#000;}
a:hover{ color:#900; text-decoration:underline;}
#main{
	margin:10px auto;
	width:90%;
	padding:15px;
	background:#fff;}
#paperList{
	width:600px;
	padding:10px;
	background:#C4E1FF;
	margin-bottom:5px;
	}
#stuNo{ width:400px;}
#sub{	
	height:22px;
	width:100px;
	text-align:center;
	border:none;
	cursor:pointer;
	background:url(../images/login_Btn_hover.gif);
	margin-left:200px; 
	margin-top:20px; 
	color:#fff;
	}
#paperList{
	width:600px;
	list-style:none;}
#paperList li{ display:none;}
#tip span{
	padding:0px 5px;
	background:#C4E1FF;
	margin-left:10px;
	cursor:pointer;
	color:#FFF;}	
#tip{
	margin-bottom:10px;}	
-->
</style>
<script type="text/javascript" src="../js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../js/jquery_corner.js"></script>
</head>
<body>
<script type="text/javascript">
	$(function(){
		$('.corner').corner('10px');
		paging();
	});
	var xmlHttpRequest;  
	//XmlHttpRequest对象 
	function createXmlHttpRequest(){ 
			if(window.ActiveXObject){ //如果是IE
					return new ActiveXObject("Microsoft.XMLHTTP"); 
			}else if(window.XMLHttpRequest){ //非IE浏览器 
					return new XMLHttpRequest(); 
			} 
	}
	//回调函数 
	function HuiDiaoFun(){ 
			if(xmlHttpRequest.readyState == 4 && xmlHttpRequest.status == 200){
					var valueReturned = xmlHttpRequest.responseText;
					document.getElementById("paperParts").innerHTML = valueReturned;
			} 
	} 
	
	//设置已选择的试卷名和试卷ID
	function setExamName(title,exam_id)
	{
		document.getElementById("examName").textContent = title;
		document.getElementById("examId").value = exam_id;		

		var url = "setreexam?exam_id="+exam_id;

		xmlHttpRequest = createXmlHttpRequest();  
		xmlHttpRequest.onreadystatechange = HuiDiaoFun;  
		xmlHttpRequest.open("post",url,true)
		xmlHttpRequest.send(null);   
	}
	//检查学号是否存在
	$(document).ready(function(){
		$('#checkStu').click(function(){
			$.post('checkstudents', {'checkStuNums': $('#studentNums').val()}, function(data){
				$('#checkResult').html(data);
			});
		});
	})       
//列表分页
function paging(){
	var len = $('#paperList li').length;
	var no = 10;  //一页显示的条数
	$('#tip span').remove();
	(function(){
		var papers = Math.ceil(len/no);
		if(papers>1){
			for(i=1;i<=papers;i++){
				var btns = "<span>"+i+"</span>";
				$('#tip').append(btns);
			}
			var show_li = '#paperList li:lt('+ no +')';
			$(show_li).show();
		}else{
			$('#paperList li').show();
		}
	})();	
	$('#tip span').live('click',function(){		
			var p = $(this).text();
			$('#paperList li').hide();
			var show_li_l = '#paperList li:lt('+  (p*no)  +')';
			var hide_li_l = '#paperList li:lt('+  (p-1)*no  +')';
			$(show_li_l).show();
			$(hide_li_l).hide();
	});
}

</script>
<div id="main" class="corner">
	<h1>设置重考</h1>
	<form name="reexamForm" action="setreexam" method="post"><br/>
	<b>选择重考考试：</b><span id="examName" style="color:#F00;"></span><br/><br/>
	<input type="hidden" id="examId" name="examId"/>
	<b>最近进行的考试</b><br>
	<ul id="paperList" class="corner">
		<?php
			if(is_array($this->getRecentlyExamList))
			{
				$i = 0;
				foreach($this->getRecentlyExamList as $value)
				{
					$i++;
					echo "<li>".$i.". <a id='".$value['id']."' href=\"JavaScript:setExamName('".$value['name']."','".$value['id']."')\">".$value['name']."</a></li>";
				}
			}else
			{
				echo $this->noSearchResult."<br>";
			}

		?>	
  </ul>
	<div id="tip">
	</div>
	选择重考部分：<br/>
	<div id="paperParts" style="width:610px; min-height:20px; border:1px #CCC solid; padding:5px;"></div><br/>
	
	输入重考学号（多个用逗号隔开，如: 111,112,113）：<br/>
	<input id="studentNums" name="studentNums" type="text" style="width:550px;" value="" />
	<input type="button" id="checkStu" value="检查考生" /> <span id="checkResult"></span><br/><br/>
	<input type="button" style="width:60px;" onClick="reexamForm.submit()" value="确定" />
	</form>
	<br/><div style="color:#F00;"><?php echo $this->msg; ?></div>
</div>
</body>
</html>
