<table id="flex1" style="display:none"></table>

	<div id="dialog">
	   <form id="dialog_form" name="dialog_form" action="#">
			<input type="hidden" name="id" />
	  <span>ID :</span><input type="text" disabled="disabled" name='dis_id' /><br/>
			<span>学号 :</span><input maxlength="11" type="text" name="username" /><br/>
			<span>姓名 :</span><input type="text" name="name" /><br/>
			<span>性别 :</span>
			<input type="radio" name="sex" checked="checked" value="男">男
			<input type="radio" name="sex" value="女">女<br/>
			<span>班级名称 :</span>
				<?php echo $this->allclassselect; ?>
			<br/>
		<span class="notice"></span>
		 <span id="okBtn">OK</span>
		 <span id="cancelBtn">Cancel</span>
	   </form>
	</div>
	<div id="alert_msg"></div>
	<div id="confirm_msg">
		<span></span><br/>
		<button id="confirm_yes">Yes</button>
		<button id="confirm_cancel">Cancel</button>
	</div>
