	<form action="#" method="post">
		<table id="tb" style="border:1px solid #000">
			<tr >
				<th>序  号</th>
				<th>编  辑</th>
				<th>学  号</th>
				<th>姓  名</th>
				<th>性  别</th>
				<th>班  级</th>
				<th>考试状态</th>
				<th colspan="2">操    作</th>
			</tr>
<?php 
$i = 0;
if(is_array($this->result)): 
	foreach($this->result as $value) : ?>
			<tr>
			<td align="center"> <?php echo ++$i; ?>
				</td>
					<td align="center"><img src="../../public/images/edit.gif" height="24px" width="24px" alt="编辑" ></img>
				</td>
				<td><input  disabled="false"  type="text" name="loginname" value="<?php echo $value['username'] ?>"/>
				</td>
				<td><input type="text" name="name" value="<?php echo $value['name'] ?>" />
				</td>
				<td><input type="text" name="gender"  value="<?php echo $value['sex'] ?> "/>
				</td>
				<td><input type="text" name="classname" value="<?php echo $this->classname ?>" />
				</td>
			<td align="center">
						<a  href="" name="restrictive" style="color:green">可  考</a>

				</td>
				<td><input  type="button" onclick="javascrip:handle(<?php echo $value['username']?>, 2)"
			  value="重置密码" />
				</td>
				<td width="60px" align="center"><img src="../../public/images/delete.gif" height="24px" width="24px" alt="删除"></img>
				</td>
			</tr>
			<?php endforeach; endif;?>
		</table>
	</form>
		<script type="text/javascript" language="javascript" >
		//显示表格效果
		$(function(){  
			$('tr:odd').css('background', 'RGB(227,222,193)')
				$("#tb tr").hover(function(){  
					$(this).addClass("td1");
				},function(){  
					$(this).removeClass("td1");  
				});
		});


//处理选项type：

function handle(username, type)
{
	switch(type) 
	{
	case 1: //编辑
	
		break;

	case 2: //重置密码
	$.post('resetpw', {'username': username , 'type': 's'}, 
			function(data) 
			{
				alert(data);
			});

	break;

	case 3://删除

		break;

	
	}

}
</script>
