<ul id="main">
	<li>
    	<p>考试设置</p>
        <ul>
        	<li><a href="manageexam" target="con">考试列表</a></li>
            <li><a href="setexam" target="con">设置考试</a></li>
            <li><a href="setreexam" target="con">设置重考</a></li>
        </ul>
    </li>
    <li>
    	<p>试卷管理</p>
        <ul>
        		<li><a href="managepaper" target="con">试卷列表</a></li>
						<li><a href="checkexamanswer" target="con">改卷</a></li>
            <li><a href="addexam" target="con">添加试卷</a></li>
            <li><a href="managecategory" target="con">试卷类别管理</a></li>
        </ul>
    </li>
    <li>
    	<p>学生管理</p>
        <ul>
        	<li><a href="managestudent" target="con">学生列表</a></li>
            <li><a href="#" target="con">快速添加学生</a></li>
        </ul>
    </li>
    <li>
    	<p>成绩信息</p>
        <ul>
        	<li><a href="managescore" target="con">本班成绩</a></li>
            <li><a href="#" target="con">年级成绩概览</a></li>
        </ul>
    </li>
    <li>
    	<p>教师管理</p>
        <ul>
        	<li><a href="manageteacher" target="con">教师列表</a></li>
            <li><a href="#" target="con">导入教师</a></li>
        </ul>
    </li>
   <li>
    	<p>班级管理</p>
        <ul>
        	<li><a href="manageclass" target="con">班级列表</a></li>
        </ul>
    </li>
    <li>
    	<p>系统设置</p>
        <ul>
        	<li><a href="#" target="con">系统公告</a></li>
            <li><a href="backup" target="con">数据备份</a></li>
        </ul>
    </li>
</ul>
