<a href="setexam">设置考试</a><br/><br/>
<a href="setreexam">设置重考</a><br/><br/>

<a href="manageleader">管理系主任</a><br/><br/>
<a href="searchleader">搜索系主任</a><br/><br/>
<a href="addleader">添加系主任</a><br/><br/>
<a href="editleader">设置系主任管理的教师</a><br/><br/>
<a href="deleteleader">删除系主任</a><br/><br/>

<a href="manageteacher">管理教师</a><br/><br/>
<a href="searchteacher">搜索教师</a><br/><br/>
<a href="addteacher">添加教师</a><br/><br/>
<a href="editteacher">编辑教师管理的班级</a><br/><br/>
<a href="deleteteacher">删除教师</a><br/><br/>

<a href="managestudent">管理学生</a><br/><br/>
<a href="searchstudent">搜索学生</a><br/><br/>
<a href="addstudent">添加学生</a><br/><br/>
<a href="editstudent">编辑学生</a><br/><br/>
<a href="deletestudent">删除学生</a><br/><br/>

<a href="manageexam">管理试卷</a><br/><br/>
<a href="searchexam">搜索试卷</a><br/><br/>
<a href="addexam">添加试卷</a><br/><br/>
<a href="editexam">编辑试卷</a><br/><br/>
<a href="deleteexam">删除试卷</a><br/><br/>

<a href="managecategory">管理分类</a><br/><br/>
<a href="addcategory">添加分类</a><br/><br/>
<a href="editcategory">编辑分类</a><br/><br/>
<a href="deletecategory">删除分类</a><br/><br/>

<a href="editscore">修改成绩</a><br/><br/>
<a href="outputscore">导出成绩</a><br/><br/>
<a href="backup">备份数据</a><br/><br/>