<ul id="main">
	<li>
    	<p>考试设置</p>
        <ul>
        	<li><a href="manageexam" target="con">考试列表</a></li>
            <li><a href="setexam" target="con">设置考试</a></li>
            <li><a href="setreexam" target="con">设置重考</a></li>
        </ul>
    </li>
    <li>
    	<p>试卷管理</p>
        <ul>
        	<li><a href="managepaper" target="con">试卷列表</a></li>
						<li><a href="checkexamanswer" target="con">改卷</a></li>
            <li><a href="addexam" target="con">添加试卷</a></li>
            <li><a href="../paper/managepapercategory" target="con">试卷类别管理</a></li>
        </ul>
    </li>
    <li>
    	<p>学生管理</p>
        <ul>
        	<li><a href="managestudent" target="con">学生列表</a></li>
            <li><a href="../../public/develop.html" target="con">导入学生</a></li>
        </ul>
    </li>
    <li>
    	<p>成绩信息</p>
        <ul>
        	<li><a href="managescore" target="con">成绩列表</a></li>
        </ul>
    </li>
    
</ul>
