<a href="setexam">设置考试</a><br/><br/>
<a href="setreexam">设置重考</a><br/><br/>

<a href="managestudent">管理学生</a><br/><br/>
<a href="searchstudent">搜索学生</a><br/><br/>
<a href="addstudent">添加学生</a><br/><br/>
<a href="editstudent">编辑学生</a><br/><br/>
<a href="deletestudent">删除学生</a><br/><br/>

<a href="manageexam">管理试卷</a><br/><br/>
<a href="searchexam">搜索试卷</a><br/><br/>
<a href="addexam">添加试卷</a><br/><br/>
<a href="editexam">编辑试卷</a><br/><br/>
<a href="deleteexam">删除试卷</a><br/><br/>

<a href="managecategory">管理分类</a><br/><br/>
<a href="addcategory">添加分类</a><br/><br/>
<a href="editcategory">编辑分类</a><br/><br/>
<a href="deletecategory">删除分类</a><br/><br/>

<a href="outputscore">导出成绩</a><br/><br/>
